# Generated by Django 6.0.7 on 2026-07-19 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('brief', models.TextField()),
                ('skills_csv', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('criteria_pending', 'Criteria pending'), ('active', 'Active'), ('delivered', 'Delivered'), ('attested', 'Attested'), ('disputed', 'Disputed')], default='draft', max_length=20)),
                ('revision_limit', models.PositiveSmallIntegerField(default=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='ledger.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CapabilityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('attested_count', models.PositiveIntegerField()),
                ('last_attested_at', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_tags', to='ledger.profile')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('profile', 'name'), name='unique_capability_tag_per_profile')],
            },
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount_cents', models.IntegerField()),
                ('timeline_days', models.IntegerField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('declined', 'Declined')], default='proposed', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='ledger.project')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gte', 0)), name='change_order_amount_cents_non_negative'), models.CheckConstraint(condition=models.Q(('timeline_days__gte', 0)), name='change_order_timeline_days_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_name_typed', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('signature_meta', models.JSONField(default=dict)),
                ('is_disputed', models.BooleanField(default=False)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('amended_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='ledger.attestation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestations', to='ledger.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('project',), name='unique_current_attestation_per_project')],
            },
        ),
        migrations.CreateModel(
            name='AcceptanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('is_passed', models.BooleanField(blank=True, null=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_items', to='ledger.project')),
            ],
            options={
                'ordering': ('order', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('project', 'order'), name='unique_acceptance_item_order_per_project')],
            },
        ),
    ]
