# Generated by Django 6.0.7 on 2026-07-27 00:52

from django.db import migrations, models


def backfill_acceptance_item_states(apps, schema_editor):
    """Derive existing item state and timestamps from project status."""
    AcceptanceItem = apps.get_model("ledger", "AcceptanceItem")
    Project = apps.get_model("ledger", "Project")
    database_alias = schema_editor.connection.alias
    project_updated_at = models.Subquery(
        Project.objects.using(database_alias)
        .filter(pk=models.OuterRef("project_id"))
        .values("updated_at")[:1]
    )

    AcceptanceItem.objects.using(database_alias).filter(
        project__status="criteria_pending",
    ).update(
        state="submitted",
        submitted_at=project_updated_at,
    )
    AcceptanceItem.objects.using(database_alias).filter(
        project__status__in=(
            "active",
            "delivered",
            "attested",
            "disputed",
        ),
    ).update(
        state="approved",
        submitted_at=project_updated_at,
        approved_at=project_updated_at,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_profile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptanceitem',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='acceptanceitem',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_acceptance_item_states,
            migrations.RunPython.noop,
        ),
    ]
