# Generated by Django 6.0.7 on 2026-07-27 23:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_acceptanceitem_approved_at_acceptanceitem_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ledger.acceptanceitem')),
            ],
            options={
                'ordering': ('order', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('item', 'order'), name='unique_acceptance_step_order_per_item')],
            },
        ),
    ]
